### PR TITLE
Added a -g option for geocoded tweets

### PR DESCRIPTION
**Pull request by hpiedcoq**
I propose this patch that adds the -g option.

Use it like : 

python3 tweep.py -g 48.880048,2.385939,1km

so 

python3 tweep.py -g lat,lon,range

You can combine with -s and --hashtags for instance.

Could be enhanced, though.

### CODE REVIEW

**Comment by hpiedcoq** [comment]
Sorry I proposed a patch few hours before you uploaded a new version of tweep.
I think that it's still relevant, no?

**Comment by haccer** [comment]
Yes, I'm reviewing it. Trying to figure out if it'll undo everything if I merge lol

**Comment by pachonk** [comment]
Git will either recursively merge or tell you there's a failure

**Comment by hpiedcoq** [comment]
So glad that you accepted this patch! Thank you!

**Pull request merged**
