### PR TITLE
pytweep -- python install functionality, iteration support, and pandas output

### PR DESCRIPTION
**Pull request by cbjrobertson**
Hi! 

I've been developing your tool (great work by the way!) for my own uses. Basically, I've made a version that functions entirely within python (admittedly because I'm better at python than I am at bash scripting). I've also integrated the script with tor_crawler, which supports ip anonymization through tor, and might help further evade detection/rate limits. I think some users might appreciate being able to use the script entirely inside python so thought I'd share in case you wanted to integrate it into the main package. FYI, this is the first time I've ever tried to contribute to something like this, so go easy please!

I don't think my scripts pyTweep.py and pyTweepTor.py should should be merged with tweep.py, as making the changes I did meant tweep could no longer be used as a command line app, but I wonder whether adding these scripts to the master repo would make more sense than keeping them on my fork. Let me know what you think:)

### CODE REVIEW

**Comment by haccer** [comment]
This is really cool, thank you! The pull request p much destroys the project, so I'm going to close it. 

I was hoping to take this direction eventually, but haven't felt the need.  
I'm going to open up a new branch so we can collaborate on a version that takes this direction

**Comment by haccer** [comment]
Please commit to this branch: [https://github.com/haccer/tweep/tree/module](https://github.com/haccer/tweep/tree/module)

Thanks :)

**Comment by cbjrobertson** [comment]
Yeah, my thoughts too! But I wanted to flag it up to see if you were interested. Cool. Will do!

**Comment by cbjrobertson** [comment]
I'll be away for a couple of weeks, but will update when I get back. Cheers.

**Comment by cbjrobertson** [comment]
Heyo-- just tried to commit to module and got a 403... do you need to edit my permissions? Also, in the module I added UnicodeDammit decoding from the bs4 package, which forces the decode into unicode and might avoid some encoding/decoding errors I noticed, and which have been raised in the issues. You might want to have a look.

**Comment by haccer** [comment]
I saw the UnicodeDammit, I'm going to look into it. Python3 is supposed to take care of that already, but it's still worth looking into. Not sure where I can edit your permissions, maybe you need the module branch in your fork. I'm still new to Github lol

**Comment by cbjrobertson** [comment]
haha. no worries. me too. I'll take it up when I get back working again.

On 3/20/18, Cody Zacharias <notifications@github.com> wrote:
> I saw the UnicodeDammit, I'm going to look into it. Python3 is supposed to
> take care of that already, but it's still worth looking into. Not sure where
> I can edit your permissions, maybe you need the module branch in your fork.
> I'm still new to Github lol
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/haccer/tweep/pull/43#issuecomment-374421694


-- 
Cole

**Pull request closed without merging**
