### PR TITLE
Added database storing option

### PR DESCRIPTION
**Pull request by pielco11**
Added two tables: users and tweets.
The first stores: who, when, how much. The second stores every tweet.
If the tweet is already stored it skips to the next one so no duplication.

### CODE REVIEW

**Comment by pielco11** [comment]
I'd like to finish some setup for Elasticsearch, I have to build the Dashboard so people will not have to build one by themselves. Give me a day.

**Comment by pielco11** [comment]
Should be fine now.

**Comment by hpiedcoq** [comment]
Sounds promising! Thanks!

**Comment by haccer** [comment]
You think we can use this instead [https://github.com/aio-libs/aioodbc](https://github.com/aio-libs/aioodbc).

Might be better for the future, also faster.

**Comment by pielco11** [comment]
I don't really see the need to use async for the database since it's faster than python. Now as now it does not slow down anything.

For what I can understand the insertion of rows in the database is already async since the function that it's calling is already async, I don't see improvements.

I'm not a DBA so I might be wrong.

**Pull request merged**
